version: '3.9'

services:
  bot:
    build: ./bot/
    restart: always
    depends_on:
      - rabbitmq
    env_file:
      - ./.env

  rabbitmq:
    image: rabbitmq:3.10.7-management
    hostname: rabbitmq
    restart: always
    env_file:
      ./.env
    volumes:
      - ./rabbitmq:/var/lib/rabbitmq
    ports:
      - 15672:15672
      # - 5672:5672